function [ unew,uold ] = functin_integrate_wave( u,uprevious,mu,h,j_int)
    uold=u; % keep the old one, as its needed in the nex iteration
%     unew = (1-2*mu)*u(j_int) + ... 
%         mu*( ...
%             u(j_int+h) + u(j_int-h) + ...
%             u(j_int+1) + u(j_int-1) ...
%             ) + ...
%             uprevious(j_int);
    unew = (2-4*mu)*u(j_int) + ... 
        mu*( ...
            u(j_int+h) + u(j_int-h) + ...
            u(j_int+1) + u(j_int-1) ...
            ) - ...
            uprevious(j_int);
end

